const data ={
    "CEO" :{"name":"V S Thejas Adithiya","desc":"Initially faced many failures in a row but a day came to build my dream, so left my past completely, with the backing of our mentor Balasubramanian sir, started Orga Plants from an initial idea till the execution here, the root cause is to build an ecosystem in which agriculture is a profitable career for the youth and not a gamble game anymore.First built a trustable team who are ready to tackle unconventional challenges to build a sustainable profitable business which ensures value creation throughout the agricultural supply chain which is our tagline.",
  "img":"../CEO.png"},
    "CDO":{"name":"MANISH THILAGAR","img":"../CDO.png","desc":"MANISH THILAGAR is a tech. enthusiast guy who loves to explore data to get meaningful insights to solve customers challenges surrounding fair pay by making use of his skills through continues exploration. Manish is responsible for the Data handling roadmap of the company. He is currently a Data analysit at Evolution Excecutive Search, he completed his BE from KIOT, salem."},
    "CTO":{"name":"Chandan Shashank","img":"../CTO.png","desc":"Chandan Shashank leads our team with his plannings ensures user happiness, with professional service approach. He's aligned with the company’s visions which believes in building a sustainable & profitable business and has done bachelor's degree from ACEIT.An Engineering Specialist with a demonstrated history of working in the sales industry, helps in team motivation, assures time and team management, and loyal leadership has strong foundation in strategy. "},
    "CPO":{"name":"Sabarishkumar T","img":"../CPO.png","desc":" Sabarish is self motivated & self built person who has previously founded Matgtech Pythonanywhere, an Edtech startup which primarily focuses on learning communityfor creators, where he oversaw product development, product management and strategy.From the day he joined us he has served as trustable and committed team member, where he focuses on software optimisation, he's pursuing his Bachelors from the College of karpagam collage of engineering. "},
    "Mentor":{"name":"","img":"../Mentor.png","desc":"The person behind building this dream is him, from day 1 when I met him he guided us further and gave his valuable time and moral support and he suggested his open opinion by his vast amount of experience.He's the Founder & CEO of ProDelta Technologies and Managing Partner at Indo Pacific Impex LLP and has a profound experience of 21 years in software services industry over a period of time Prodelta has built expertise in different technologies in Web, Mobile, Internet of things (IOT), Artificial intelligence."},
    "Design":{"name":"","img":"../Design.png","desc":" Self made consistent team player who works tirelessly to make wonders happen, switching career to Design and to mention a innovative UI/UX designer.From the day she joined us served as trustable and committed team member, where she focuses on design and product innovation, has pursed her Bachelors  of Science."}
  }

export default data